version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nutrigpt-dev
    networks:
      - nutrigpt-network

  nutrigpt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3333
    depends_on:
      - dev-db
    networks:
      - nutrigpt-network
    environment:
      DATABASE_URL: postgres://postgres:12345@dev-db:5432/nutrigpt-dev
networks:
  nutrigpt-network:
